# Workflow personalizzato per pubblicare il portfolio statico su GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Permessi espliciti richiesti per la pubblicazione di GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permette una sola pubblicazione alla volta
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Configurazione Pages
        uses: actions/configure-pages@v4

      - name: Caricamento dei file del sito (Artifact)
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Carica tutti i file nella root del progetto

      - name: Pubblicazione su GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
